module.exports={
    PRODUCT_COLLECTIOS:'product',
    USER_COLLECTION:'user',
    CATEGORY_COLLECTION:'category',
    SUB_COLLECTION:'subcategory',
    CART_COLLECTION:'cart',
    USER_ADDRESS_COLLECTION:'Adress',
    ORDER_COLLECTION:'order'
}